src/app/layouts/pageForm.ejs
src/app/layouts/pageLink.ejs
src/app/layouts/pagination.ejs
src/app/services/index.js
src/app/services/newServiceBanner.js
src/app/services/serviceBanners.js
src/app/services/views/newServiceBanner.ejs
src/app/services/views/serviceBanners.ejs
src/infrastructure/applications/api.js
src/infrastructure/applications/static.js
test/app/services/getNewServiceBanner.test.js
test/app/services/getServiceBanners.test.js
test/app/services/postNewServiceBanner.test.js

NSA-1934 and NSA-1856 - create and edit banner

Nsa 1934 create banner

---

src/app/services/getDashboard.js
src/app/services/index.js
src/app/services/selectService.js
src/app/services/views/dashboard.ejs
src/infrastructure/utils/index.js
test/app/services/getSelectService.test.js

Allow access to certain parts of manage based on roles

Nsa 2028 manage access

---

azure/parameters.json
azure/template.json

Initial commit needed for app service tenplate.

Adding Azure base template

---

package-lock.json
package.json
src/app/services/confirmEditService.js
src/app/services/editService.js
src/app/services/getUserOrganisations.js
src/app/services/index.js
src/app/services/views/confirmEditService.ejs
src/app/services/views/editService.ejs
src/app/services/views/summaryPartial.ejs
src/app/services/views/userOrganisations.ejs
src/infrastructure/access/api.js
src/infrastructure/access/static.js
test/app/services/confirmEditService.get.test.js
test/app/services/confirmEditService.post.test.js
test/app/services/editService.get.test.js
test/app/services/editService.post.test.js
test/app/services/getUserOrganisations.test.js

This PR covers both NSA-1926 and NSA-1928

Nsa-1926 support edit service

---

src/infrastructure/utils/index.js

Fix bug in middleware, make sure user has role for specific service rather than just the existence of the role

NSA-2092- check hasRole for service

---

src/app/services/serviceConfig.js
src/app/services/views/serviceConfig.ejs
test/app/services/getServiceConfig.test.js
test/app/services/postServiceConfig.test.js

Fix validation on urls. And fix problem that caused wiping of inputted fields if validation error occurs.

Nsa 2084 service config validation

---

azure/parameters.json
azure/template.json

Update Azure templates

---

src/app/layouts/layout.ejs

Jira ticket: https://dfe-secureaccess.atlassian.net/browse/NSA-5447

NSA-5447- Added the 'Accessibility statement' link in the footer

---

src/app/services/selectService.js
src/app/services/views/selectService.ejs
test/app/services/postSelectService.test.js

Jira ticket : https://dfe-secureaccess.atlassian.net/browse/NSA-6126

NSA-6126 updated select service page to latest GDS design

---

package-lock.json
src/app/services/views/confirmEditService.ejs
src/app/services/views/confirmResendInvitation.ejs
src/app/services/views/editService.ejs
src/app/services/views/removeService.ejs
src/app/services/views/summaryPartial.ejs
src/app/services/views/userOrganisations.ejs
src/app/services/views/usersSearch.ejs
src/app/services/views/webServiceSync.ejs

Updated the following pages to the latest GDS design as part of Jira ticket https://dfe-secureaccess.atlassian.net/browse/NSA-5554:
- summaryPartial.ejs
- userOrganisations.ejs
- editService.ejs
- removeService.ejs
- webServiceSync.ejs
- confirmEditService.ejs
- confirmResendInvitation.ejs

feature/NSA-6166_Resend invitation email journeys GDS upgrade

---

src/app/layouts/layout.ejs

Jira ticket: https://dfe-secureaccess.atlassian.net/browse/NSA-6314
- Added Organisations link to the nav bar

NSA-6314 - Added Organisations to the nav bar

---

src/app/services/organisationsSearch.js
src/app/services/utils.js
src/app/services/views/organisationsSearch.ejs
src/infrastructure/organisations/api.js
test/app/services/organisationsSearch.test.js

Jira ticket https://dfe-secureaccess.atlassian.net/browse/NSA-6313: 
- added UPIN column to the organisations search table - we don't have data yet for it and because of that it is not sortable
- made all the table columns sortable 
- updated Organisation search template to the lates UI design
- fixed the back links

feature/NSA-6313 - order organisation search

---

src/app/services/views/organisationsSearch.ejs

Jira ticket: https://dfe-secureaccess.atlassian.net/browse/NSA-6313

NSA-6313 - Updated organisation table header name

---

src/app/services/usersSearch.js
src/app/services/views/usersSearch.ejs

Jira ticket: https://dfe-secureaccess.atlassian.net/browse/NSA-6373

NSA-6373 - UsersSearch - removed sorting by organisation

---

src/app/services/views/usersSearch.ejs

Jira ticket: https://dfe-secureaccess.atlassian.net/browse/NSA-2995

NSA-2995 - User search box updated content with legacy ID

---

src/app/layouts/layout.ejs
src/app/services/index.js
src/app/services/serviceSecrets.js
src/app/services/views/dashboard.ejs
src/app/services/views/serviceSecrets.ejs
test/app/services/serviceSecrets.get.test.js
test/app/services/serviceSecrets.post.test.js

Jira ticket: 
https://dfe-secureaccess.atlassian.net/browse/NSA-6258
Implemented the new page for Service secrets page 
Service secrets manage role needed to access it

feature/NSA - 6258 implement service secrets page

---

src/app/services/organisationUserList.js
src/app/services/views/_organisationSummary.ejs
src/app/services/views/organisationUserList.ejs
test/app/services/organisationUserList.test.js

Jira ticket:
https://dfe-secureaccess.atlassian.net/browse/NSA-6544

NSA-6544 - Display all users associated with org

---

src/app/services/getServiceInfo.js
src/app/services/index.js
src/app/services/views/dashboard.ejs
src/app/services/views/serviceInfo.ejs
test/app/services/getServiceInfo.test.js

Jira ticket: 
https://dfe-secureaccess.atlassian.net/browse/NSA-6262

[NSA-6262] Add service info panel and page

---

src/app/services/views/userOrganisations.ejs

Jira ticket: https://dfe-secureaccess.atlassian.net/browse/NSA-6964

[NSA-6964] - Added legacy name to user orgs list

---

src/app/services/views/dashboard.ejs

https://dfe-secureaccess.atlassian.net/browse/NSA-7083

changes user manage tile content

---

src/app/layouts/layout.ejs

Jira ticket:
https://dfe-secureaccess.atlassian.net/browse/NSA-7463
Changes:
Added Help link to the Navigation Ribbon for Manage Console menu

[NSA-7463] Add help section to manage ribbon

---

src/app/services/views/serviceConfig.ejs

Jira ticket:
https://dfe-secureaccess.atlassian.net/browse/NSA-7464
Changes:
- updated linking between the Service configuration changes page and the relevant section on the Help page.

[NSA-7464] - added links to the help page sections

---

src/app/services/views/userOrganisations.ejs

broke the return link at review stage now fixed

commit fix to broken link return

---

src/app/services/utils.js
src/app/services/views/serviceConfig.ejs
src/constants/serviceConfigConstants.js
test/app/services/confirmServiceConfig.get.test.js
test/app/services/confirmServiceConfig.post.test.js
test/app/services/postServiceConfig.test.js

Jira ticket: https://dfe-secureaccess.atlassian.net/browse/NSA-7418
Changes: updates to the error message content on the service configuration form page

[NSA-7418] Service config page form validation updates

---

src/app/layouts/filters.ejs
src/app/services/usersSearch.js
src/app/services/utils.js
src/app/services/views/usersSearch.ejs
src/infrastructure/utils/index.js

Jira ticket: https://dfe-secureaccess.atlassian.net/browse/NSA-7270
Changes:
-implemented filter functionality to the User search page

[NSA-7270] User search - filtering implementation

---

src/app/services/organisationsSearch.js
src/app/services/usersSearch.js

Jira ticket: https://dfe-secureaccess.atlassian.net/browse/NSA-6273
Changes:
- code changes to allow special characters to be passed into the Cognitive search

[NSA-6273] Updates to user and org search feature

---

package.json
src/app/services/views/serviceConfig.ejs

[NSA-7626-test](https://dfe-secureaccess.atlassian.net/browse/DSI-6517)
make links open in new tab

add new tab link

---

src/app/services/serviceConfig.js
src/app/services/views/serviceConfig.ejs

fix the encoding in the bottom view had to change views to display without encoding

fixed bottom two views

---

src/app/services/serviceConfig.js
test/app/services/postServiceConfig.test.js

fixed system to allow reset password and homeservice url to be blank

fixed blank url

---

src/app/services/views/associateRoles.ejs

Reverts DFE-Digital/login.dfe.manage#248
No need for this change

Revert "PIM-2549"

---

src/app/services/views/newServiceBanner.ejs

Jira issue https://dfe-secureaccess.atlassian.net/browse/DSI-6821
Requirement
As a user of DSI
Screen reading software to identify there has been an error and vocalise if there is an error or suggest a solution in
aria-describedby
How fieldset class is listed in the error message page
Solution: Updated missing html markup in ejs files i.e **aria-describedby**
**Recommended in** GDS Design control https://design-system.service.gov.uk/components/error-message/
**Accessibility plugin used for testing** https://chromewebstore.google.com/detail/accessibility-a-powerful/nnmmmhcflgbendklbhknkkacnjempijd

DSI-6821 Added html mark up for validation-selected-organisation tag

---

package-lock.json
package.json
src/app/services/views/dashboard.ejs

Jira ticket: [DSI-6615](https://dfe-secureaccess.atlassian.net/browse/DSI-6615)
- Updated heading text.
- Fixed three moderate and three high severity vulnerability using `npm audit fix`.
- Fixed vulnerabilities related to tedious package.
- https://github.com/DFE-Digital/login.dfe.services/pull/593
- https://github.com/DFE-Digital/login.dfe.profile/pull/309

[DSI-6615] Review page summaries across the DfE Sign-in service - update statement in blue textbox 

---

package-lock.json
package.json

Link to ticket: [NSA-8691](https://dfe-secureaccess.atlassian.net/browse/NSA-8691)
Updated validations version in package.json

[NSA-8691] Update DfE package versions

---

src/app/services/getUserOrganisations.js
test/app/services/getUserOrganisations.test.js

Link to ticket: [NSA-8704](https://dfe-secureaccess.atlassian.net/browse/NSA-8704)
- Sorting user services and roles alphabetically 
- updated tests

[NSA-8704] DSi Manage - display services alphabetically

---

package-lock.json
src/app/helpers/dateFormatterHelper.js
src/app/services/deleteServiceBanner.js
src/app/services/getAudit.js
src/app/services/organisationUserList.js
src/app/services/serviceBanners.js
src/app/services/usersSearch.js
src/app/services/utils.js
src/app/services/views/audit.ejs
src/app/services/views/deleteServiceBanner.ejs
src/app/services/views/organisationUserList.ejs
src/app/services/views/serviceBanners.ejs
src/app/services/views/summaryPartial.ejs
src/app/services/views/usersSearch.ejs
src/index.js
test/app/helpers/dateFormatterHelper.test.js

Jira ticket: [DSI-6665](https://dfe-secureaccess.atlassian.net/browse/DSI-6665)
- Ensured consistent Date and Time formatting.
- Fixed 2 moderate severity vulnerability using `npm audit fix`.
- Created time helper function for a consistent date format.
- https://github.com/DFE-Digital/login.dfe.services/pull/614
- https://github.com/DFE-Digital/login.dfe.support/pull/520

[DSI-6665] Ensure there is consistent Date and Time formatting
